name:                kafka
version:             0.1.0.0
github:              "ekalosak/kafka"
license:             BSD3
author:              "Eric Kalosa-Kenyon"
maintainer:          "helloateric@gmail.com"
copyright:           "2019 Eric Kalosa-Kenyon"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Haskell / Kafka integration POC
# category:            Data Pipeline

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/ekalosak/kafka#readme>

dependencies:
- base >= 4.7 && < 5
- hw-kafka-client
- text
- bytestring

library:
  source-dirs: src

executables:
  kafka-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - kafka

tests:
  kafka-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - kafka
